from enum import Enum


class ShipmentStatus(str, Enum):
    CREATED = "CREATED"
    DROPPED_OFF = "DROPPED_OFF"
    TARIFF_CALCULATED = "TARIFF_CALCULATED"
    PAID = "PAID"
    QR_GENERATED = "QR_GENERATED"
    DOCUMENTS_CREATED = "DOCUMENTS_CREATED"
    STORED_IN_CELL = "STORED_IN_CELL"
    LOADED = "LOADED"
    IN_TRANSIT = "IN_TRANSIT"
    ARRIVED = "ARRIVED"
    NOTIFIED = "NOTIFIED"
    ISSUED = "ISSUED"
    CLOSED = "CLOSED"
